# Generated by Django 4.0.5 on 2022-12-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='email',
            new_name='email_course',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='name_course',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='password',
            new_name='password_course',
        ),
    ]
